#!/usr/bin/env python3
"""Generate manuscript numbers and their output-level provenance registry."""

from __future__ import annotations

import csv
import json
from pathlib import Path

import pandas as pd

ROOT=Path(__file__).resolve().parents[1]


def pct(x:float)->str: return f"{100*x:.1f}"


def main()->None:
    sim=json.loads((ROOT/"simulation/outputs/summary.json").read_text())
    emp=json.loads((ROOT/"empirical/outputs/summary.json").read_text())
    defs=pd.read_csv(ROOT/"empirical/outputs/definition_summary.csv").set_index("ranking_definition")
    years=pd.read_csv(ROOT/"empirical/outputs/year_heterogeneity.csv")
    lag=pd.read_csv(ROOT/"empirical/outputs/lagged_2024_validation.csv")
    nat=pd.read_csv(ROOT/"empirical/outputs/national_check.csv")
    conv=pd.read_csv(ROOT/"simulation/outputs/convergence_summary.csv")
    values={
        "NStates":(emp["states"],"states","empirical/outputs/summary.json","states"),
        "NStateYears":(emp["complete_state_years"],"state-years","empirical/outputs/summary.json","complete_state_years"),
        "NCropRows":(emp["complete_panel_rows"],"crop rows","empirical/outputs/summary.json","complete_panel_rows"),
        "EmpiricalStartYear":(2022,"year","empirical/configs/empirical_design.yaml","start_year"),
        "EmpiricalEndYear":(2024,"year","empirical/configs/empirical_design.yaml","end_year"),
        "OperatingTopCount":(63,"state-years","empirical/outputs/discordance_detail.csv","sum top_rank_reversal"),
        "OperatingTopRate":(pct(defs.loc["operating_margin","top_rank_reversal_rate"]),"percent","empirical/outputs/definition_summary.csv","operating_margin.top_rank_reversal_rate"),
        "OperatingStrongCount":(41,"state-years","empirical/outputs/discordance_detail.csv","sum strong_reversal"),
        "OperatingStrongRate":(pct(defs.loc["operating_margin","strong_reversal_rate"]),"percent","empirical/outputs/definition_summary.csv","operating_margin.strong_reversal_rate"),
        "DefinitionMinRate":(pct(defs.top_rank_reversal_rate.min()),"percent","empirical/outputs/definition_summary.csv","min top_rank_reversal_rate"),
        "DefinitionMaxRate":(pct(defs.top_rank_reversal_rate.max()),"percent","empirical/outputs/definition_summary.csv","max top_rank_reversal_rate"),
        "LaggedStates":(len(lag),"states","empirical/outputs/lagged_2024_validation.csv","rows"),
        "LaggedTopCount":(int(lag.top_rank_reversal.sum()),"states","empirical/outputs/lagged_2024_validation.csv","sum top_rank_reversal"),
        "LaggedTopRate":(pct(lag.top_rank_reversal.mean()),"percent","empirical/outputs/lagged_2024_validation.csv","mean top_rank_reversal"),
        "NationalComparisons":(len(nat),"crop-years","empirical/outputs/national_check.csv","rows"),
        "NationalReversals":(int(nat.rank_reversal.sum()),"crop-years","empirical/outputs/national_check.csv","sum rank_reversal"),
        "SimulationCells":(sim["formal_cells"],"design cells","simulation/outputs/summary.json","formal_cells"),
        "SimulationReplications":(sim["formal_replications"],"replications","simulation/outputs/summary.json","formal_replications"),
        "UniversalReplications":(sim["universal_reversal_replications"],"replications","simulation/outputs/summary.json","universal_reversal_replications"),
        "RiskBindingReplications":(sim["risk_binding_replications"],"replications","simulation/outputs/summary.json","risk_binding_replications"),
        "RiskSlackReplications":(sim["formal_replications"]-sim["risk_binding_replications"],"replications","simulation/outputs/summary.json","derived formal minus binding"),
        "PseudoDiversificationReplications":(sim["pseudo_diversification_replications"],"replications","simulation/outputs/summary.json","pseudo_diversification_replications"),
        "ReplayPasses":(sim["independent_replay_passes"],"replications","simulation/outputs/summary.json","independent_replay_passes"),
        "SolverPasses":(sim["solver_sensitivity_passes"],"comparisons","simulation/outputs/summary.json","solver_sensitivity_passes"),
        "ConvergencePassRows":(int(conv.convergence_pass.sum()),"grid rows","simulation/outputs/convergence_summary.csv","sum convergence_pass"),
        "ConvergenceRows":(len(conv),"grid rows","simulation/outputs/convergence_summary.csv","rows"),
        "ConvergenceWidth":(f"{conv.reversal_probability_interval_width.max():.3f}","probability","simulation/outputs/convergence_summary.csv","max reversal_probability_interval_width"),
    }
    generated=ROOT/"manuscript/generated"; generated.mkdir(parents=True,exist_ok=True)
    lines=["% Generated by scripts/generate_manuscript_inputs.py; do not edit."]
    registry=[]
    for macro,(value,unit,path,field) in values.items():
        lines.append(f"\\newcommand{{\\{macro}}}{{{value}}}")
        registry.append({"macro":macro,"displayed_value":value,"unit":unit,"output_file":path,"output_field":field,"generation_command":"python scripts/generate_manuscript_inputs.py","verification_status":"VERIFIED"})
    (generated/"numbers.tex").write_text("\n".join(lines)+"\n",encoding="utf-8")
    reg=ROOT/"manuscript/registries"; reg.mkdir(parents=True,exist_ok=True)
    with (reg/"number_output.csv").open("w",newline="",encoding="utf-8") as handle:
        writer=csv.DictWriter(handle,fieldnames=registry[0].keys()); writer.writeheader(); writer.writerows(registry)
    original=pd.read_csv(ROOT/"audits/draft_content_completion_matrix.csv")
    def destination(cid:str)->str:
        n=int(cid[1:])
        if n in {2,41}: return "manuscript/sections/related_literature.tex;references.bib"
        if 3<=n<=21: return "manuscript/sections/model.tex;manuscript/sections/methods.tex"
        if 22<=n<=30: return "manuscript/sections/structural_results.tex;supplementary/sections/theory_proofs.tex"
        if 31<=n<=34: return "manuscript/sections/numerical_experiments.tex;supplementary/sections/numerical_protocol.tex"
        if 35<=n<=38: return "manuscript/sections/data_empirical_design.tex;manuscript/sections/empirical_results.tex;manuscript/sections/robustness_extensions.tex"
        if n==39: return "manuscript/sections/discussion.tex"
        if n==40: return "manuscript/sections/conclusion.tex"
        if n==42: return "manuscript/registries/figure_table_usage.csv"
        if n==43: return "supplementary/supplementary.tex"
        if n==44: return "manuscript/main.tex;supplementary/supplementary.tex"
        return "manuscript/sections/introduction.tex"
    dispositions=pd.DataFrame({"content_id":original.content_id,"content_summary":original.content_summary,"issue_9_destination":[destination(c) for c in original.content_id],"final_status":"CLOSED_ISSUE_9","boundary_or_replacement":original.canonical_disposition})
    dispositions.to_csv(reg/"draft_completion_disposition.csv",index=False,lineterminator="\n")
    print(f"generated_macros={len(values)} completion_rows={len(dispositions)}")


if __name__=="__main__": main()
